name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Install, Lint, Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: node --version
      - run: npm --version
      - run: npm ci
      - run: npm run lint
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
